- name: "Update apt cache and upgrade all packages"

  # FQCN どの道具箱から道具を取り出すか。
  # `ansible`: 開発元, `builtin`: Ansible本体に最初から内蔵されている、最も信頼性の高い標準ツール群
  ansible.builtin.apt:
      upgrade: "dist" # OSに入っている既存のパッケージを安全に更新する。依存関係も含めて、OS全体を最新の状態の最適化する `apt dist-upgrade`相当。初期構築痔はこれを使うのが一般的。
      update_cache: true # インストール前にパッケージ情報を最新に更新する。`apt update` を行う。

- name: "Install basic packages"
  ansible.builtin.apt:
      name:
          - "curl"
          - "git"
          - "vim"
          - "ufw"
      state: "present" # そのパッケージを最終的にどうしたいか (べき等性)。 インストールされていることをゴールにする。`absent`: アンインストールされていることをゴールに、`latest`: 常に最新版が入っていることをゴールにする。

- name: "Set timezone to Asia/Tokyo"
  ansible.builtin.timezone:
      name: Asia/Tokyo

# UFW (Cncomplicated Firewall)
# SSH (22), HTTP (80) をOpen
- name: "Allow SSH traffic"
  ansible.builtin.ufw:
      rule: "allow" # 指定した通信を許可
      port: "22"
      proto: "tcp"

- name: "Allow HTTP traffic"
  ansible.builtin.ufw:
      rule: "allow"
      port: "80"
      proto: "tcp"

- name: "Allow HTTPS traffic"
  ansible.builtin.ufw:
      rule: "allow"
      port: "443"
      proto: "tcp"

- name: "Enabled UFW and set default deny policy"
  ansible.builtin.ufw:
      state: "enabled" # ファイアウォール機能を有効化し、OS起動時にも自動適用されるようにする。
      policy: "deny" # 「デフォルト拒否」の設定。ルールに書かれていない未知の通信はこのポリシーによって遮断。
      direction: "incoming" # 外部からサーバへ「入ってくる」通信に対し、制限をかける。
